#!/usr/bin/with-contenv bash

if [ "${SKIP_SSL,,}" = true ]; then
  envsubst '${ADMIN_USER} ${ADMIN_PASS} ${ADMIN_AUTH}' < /defaults/default.http > /defaults/default
else
  envsubst '${ADMIN_USER} ${ADMIN_PASS} ${ADMIN_AUTH}' < /defaults/default.https > /defaults/default
fi
